version: "3"

services:
  app:
    build: .
    environment:
      MONGODB_HOST: mongo
      MONGODB_PORT: 27017
      MONGODB_AUTH_DATABASE: admin
      MONGODB_USER_NAME: root
      MONGODB_USER_PASSWORD: password
      MONGODB_COLLECTION_NAME: challenge
    ports:
      - 8080:8080
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: challenge
    ports:
      - 27017:27017