# MongoDB config
spring:
  data:
    mongodb:
      authentication-database: ${MONGODB_AUTH_DATABASE}
      username: ${MONGODB_USER_NAME}
      password: ${MONGODB_USER_PASSWORD}
      database: ${MONGODB_COLLECTION_NAME}
      port: ${MONGODB_PORT}
      host: ${MONGODB_HOST}